"""
Authentica AI — Main Streamlit Application Portal.
"""
import streamlit as st

st.set_page_config(
    page_title="Authentica AI — Multimodal Content Detection",
    page_icon="🛡️",
    layout="wide",
    initial_sidebar_state="expanded",
)

# Custom CSS for polished, professional typography and cards
st.markdown(
    """
    <style>
    .main-title {
        font-size: 2.6rem;
        font-weight: 800;
        color: #1E3A8A;
        margin-bottom: 0.2rem;
    }
    .sub-title {
        font-size: 1.2rem;
        color: #4B5563;
        margin-bottom: 1.5rem;
    }
    .card {
        background-color: #F8FAFC;
        border-radius: 10px;
        padding: 1.5rem;
        border: 1px solid #E2E8F0;
        margin-bottom: 1rem;
    }
    .badge-info {
        background-color: #EFF6FF;
        color: #1D4ED8;
        padding: 0.25rem 0.6rem;
        border-radius: 6px;
        font-size: 0.85rem;
        font-weight: 600;
        display: inline-block;
    }
    .disclaimer-box {
        background-color: #FFFBEB;
        border-left: 4px solid #F59E0B;
        padding: 1rem;
        border-radius: 4px;
        margin-top: 1.5rem;
        font-size: 0.95rem;
        color: #92400E;
    }
    </style>
    """,
    unsafe_allow_html=True,
)

st.markdown('<div class="main-title">🛡️ Authentica AI</div>', unsafe_allow_html=True)
st.markdown(
    '<div class="sub-title">An Academic Multimodal AI-Generated Content Detection System</div>',
    unsafe_allow_html=True,
)

col1, col2 = st.columns([3, 2])

with col1:
    st.markdown("### 🔍 System Overview")
    st.write(
        """
        **Authentica AI** is an academic-grade multimodal detection platform designed to analyze 
        digital content—**Images, Text, Audio, and Video**—and estimate the likelihood of AI generation 
        versus authentic human creation.
        
        Rather than treating AI detection as an absolute binary determination, Authentica AI operates 
        under a **probabilistic decision framework** that explicitly quantifies uncertainty, provides 
        linguistic and visual evidence, and maintains strict scientific evaluation standards.
        """
    )

    st.markdown("### 🧭 Core Capabilities")
    c1, c2 = st.columns(2)
    with c1:
        st.markdown(
            """
            * **🖼️ Image Detection:** Vision Transformer (`umm-maybe/AI-image-detector`) trained on diffusion artifacts (Midjourney, Stable Diffusion, DALL-E).
            * **📝 Text Detection:** RoBERTa transformer (`Hello-SimpleAI/chatgpt-detector-roberta`) with sliding-window multi-chunk aggregation.
            """
        )
    with c2:
        st.markdown(
            """
            * **🎵 Audio Detection:** Wav2Vec2 sequence classifier fine-tuned for synthetic speech and voice clones.
            * **🎬 Video Late Fusion:** Multi-stream temporal keyframe extraction combined with demuxed audio analysis.
            """
        )

with col2:
    st.markdown("### 📊 Decision Framework")
    st.info(
        """
        **Three-Way Decision Verdicts:**
        * 🔴 **LIKELY AI-GENERATED** ($S_{\\text{AI}} \\ge 0.65$)
        * 🟢 **LIKELY HUMAN-CREATED** ($S_{\\text{AI}} \\le 0.35$)
        * 🟡 **UNCERTAIN** ($0.35 < S_{\\text{AI}} < 0.65$)
        
        *Scores represent uncalibrated model softmax estimates.*
        """
    )
    
    st.markdown("### 🚀 Quick Navigation")
    st.markdown(
        """
        * Navigate to **[🔍 Detect Content](1_Detect_Content)** to submit images, text, or multimedia.
        * Navigate to **[📊 Model Performance](2_Model_Performance)** to review real benchmark metrics and ROC curves.
        * Navigate to **[ℹ️ About](3_About)** for research methodology, model cards, and ethics.
        """
    )

st.markdown(
    """
    <div class="disclaimer-box">
        <strong>⚖️ Standard Probabilistic Disclaimer:</strong><br>
        This result is an AI-based estimate and is not definitive proof of whether the content was generated by AI. 
        Detection performance may vary across different generation models, compression levels, and editing workflows.
    </div>
    """,
    unsafe_allow_html=True,
)
