"""
Authentica AI — Reusable Probabilistic Disclaimer Component.
"""
import streamlit as st


def render_disclaimer() -> None:
    disclaimer_html = """<div style="background: rgba(30, 41, 59, 0.5); border: 1px solid #334155; border-left: 4px solid #3B82F6; border-radius: 8px; padding: 0.9rem 1.2rem; margin-top: 1.2rem; margin-bottom: 1.2rem; font-size: 0.86rem; color: #94A3B8; line-height: 1.55;">
<strong style="color: #CBD5E1;">⚖️ Probabilistic Guidance Notice:</strong>
This result is an AI-based estimate and is not definitive proof of whether the content was generated by AI.
Detection performance is model-dependent and influenced by training distributions, generator architectures, compression artifacts, and resolution scaling.
</div>"""
    st.markdown(disclaimer_html, unsafe_allow_html=True)
