"""
Abstract Base Detector interface and standardized DetectionResult dataclass for Authentica AI.
"""
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, Optional

from src.core.config import ThresholdConfig


class Verdict(str, Enum):
    LIKELY_AI = "LIKELY AI-GENERATED"
    LIKELY_HUMAN = "LIKELY HUMAN-CREATED"
    UNCERTAIN = "UNCERTAIN"


class ConfidenceLevel(str, Enum):
    HIGH = "High"
    MEDIUM = "Medium"
    LOW = "Low"


@dataclass(frozen=True)
class DetectionResult:
    """
    Standardized result contract returned by all Authentica AI detectors.
    """
    modality: str
    score: float                            # Uncalibrated AI detection score in [0.0, 1.0]
    verdict: Verdict
    confidence: ConfidenceLevel
    model_name: str
    model_version: str
    processing_time_ms: float
    disclaimer: str
    is_calibrated: bool = False
    evidence: Dict[str, Any] = field(default_factory=dict)
    error: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "modality": self.modality,
            "score": round(self.score, 4),
            "verdict": self.verdict.value,
            "confidence": self.confidence.value,
            "model_name": self.model_name,
            "model_version": self.model_version,
            "processing_time_ms": round(self.processing_time_ms, 2),
            "is_calibrated": self.is_calibrated,
            "disclaimer": self.disclaimer,
            "evidence": self.evidence,
            "error": self.error,
        }


def compute_verdict_and_confidence(
    ai_score: float,
    threshold_cfg: Optional[ThresholdConfig] = None,
) -> tuple[Verdict, ConfidenceLevel]:
    """
    Classifies continuous AI score into 3-way verdict and confidence level.
    Score S_AI in [0.0, 1.0]:
      - S_AI >= upper_threshold -> LIKELY AI-GENERATED
      - S_AI <= lower_threshold -> LIKELY HUMAN-CREATED
      - otherwise              -> UNCERTAIN
    """
    cfg = threshold_cfg or ThresholdConfig()
    ai_score = max(0.0, min(1.0, float(ai_score)))

    if ai_score >= cfg.upper_threshold:
        verdict = Verdict.LIKELY_AI
        # Higher distance above upper threshold means higher confidence
        confidence = ConfidenceLevel.HIGH if ai_score >= 0.85 else ConfidenceLevel.MEDIUM
    elif ai_score <= cfg.lower_threshold:
        verdict = Verdict.LIKELY_HUMAN
        # Lower score below lower threshold means higher confidence
        confidence = ConfidenceLevel.HIGH if ai_score <= 0.15 else ConfidenceLevel.MEDIUM
    else:
        verdict = Verdict.UNCERTAIN
        confidence = ConfidenceLevel.LOW

    return verdict, confidence


class BaseDetector(ABC):
    """
    Abstract Base Class for all modality detectors in Authentica AI.
    """

    def __init__(self, model_id: str, threshold_cfg: Optional[ThresholdConfig] = None):
        self.model_id = model_id
        self.threshold_cfg = threshold_cfg or ThresholdConfig()
        self._model = None
        self._preprocessor = None

    @abstractmethod
    def load_model(self) -> None:
        """Loads and initializes the underlying AI model and tokenizer/feature extractor."""
        pass

    @abstractmethod
    def preprocess(self, raw_input: Any) -> Any:
        """Validates and preprocesses raw input into model tensor format."""
        pass

    @abstractmethod
    def predict(self, preprocessed_input: Any) -> float:
        """Executes forward pass and returns uncalibrated AI score in [0.0, 1.0]."""
        pass

    def classify(self, raw_input: Any) -> DetectionResult:
        """
        End-to-end execution: preprocess -> predict -> compute verdict & return structured result.
        """
        import time
        start_time = time.perf_counter()

        preprocessed = self.preprocess(raw_input)
        ai_score = self.predict(preprocessed)
        elapsed_ms = (time.perf_counter() - start_time) * 1000.0

        verdict, confidence = compute_verdict_and_confidence(ai_score, self.threshold_cfg)

        return DetectionResult(
            modality=getattr(self, "MODALITY", "unknown"),
            score=ai_score,
            verdict=verdict,
            confidence=confidence,
            model_name=self.model_id,
            model_version="1.0.0",
            processing_time_ms=elapsed_ms,
            disclaimer="This result is an AI-based estimate and is not definitive proof of whether the content was generated by AI.",
            is_calibrated=False,
            evidence={"raw_ai_score": round(ai_score, 4)},
        )
