"""
Configuration loader and management for Authentica AI.
"""
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple
import yaml

from src.core.exceptions import ValidationError


@dataclass(frozen=True)
class AppConfig:
    name: str = "Authentica AI"
    tagline: str = "Multimodal AI-Generated Content Detection System"
    version: str = "1.0.0"
    disclaimer: str = "This result is an AI-based estimate and is not definitive proof of whether the content was generated by AI."


@dataclass(frozen=True)
class ThresholdConfig:
    upper_threshold: float = 0.45  # S_AI > 0.45  -> LIKELY AI-GENERATED
    lower_threshold: float = 0.40  # S_AI < 0.40  -> LIKELY HUMAN-CREATED
    # 0.40 <= S_AI <= 0.45        -> UNCERTAIN

    def validate(self) -> None:
        if not (0.0 <= self.lower_threshold < self.upper_threshold <= 1.0):
            raise ValidationError(
                f"Invalid threshold range: lower ({self.lower_threshold}) must be < upper ({self.upper_threshold}) within [0.0, 1.0]"
            )



@dataclass(frozen=True)
class ImageModelConfig:
    primary: str = "umm-maybe/AI-image-detector"
    baseline: str = "capcheck/ai-image-detection"
    device: str = "auto"
    batch_size: int = 1
    input_size: Tuple[int, int] = (224, 224)


@dataclass(frozen=True)
class TextModelConfig:
    primary: str = "Hello-SimpleAI/chatgpt-detector-roberta"
    multilingual: str = "yaya36095/xlm-roberta-text-detector"
    device: str = "auto"
    max_length: int = 512
    min_character_length: int = 50
    chunk_overlap: int = 50


@dataclass(frozen=True)
class AudioModelConfig:
    primary: str = "garystafford/wav2vec2-deepfake-voice-detector"
    baseline: str = "Sara1708/deepfake-audio-wav2vec2"
    device: str = "auto"
    target_sample_rate: int = 16000
    chunk_duration_sec: float = 4.0


@dataclass(frozen=True)
class VideoModelConfig:
    sample_frames: int = 8
    max_duration_sec: int = 50
    visual_weight: float = 0.6
    audio_weight: float = 0.4

    def validate(self) -> None:
        if abs((self.visual_weight + self.audio_weight) - 1.0) > 1e-4:
            raise ValidationError(f"Video fusion weights must sum to 1.0: got {self.visual_weight} + {self.audio_weight}")


@dataclass(frozen=True)
class SecurityConfig:
    max_image_size_mb: int = 25
    max_audio_size_mb: int = 50
    max_video_size_mb: int = 250
    max_text_characters: int = 50000
    allowed_extensions: Dict[str, List[str]] = field(default_factory=lambda: {
        "image": [".jpg", ".jpeg", ".png", ".webp", ".bmp"],
        "audio": [".wav", ".mp3", ".flac", ".ogg", ".m4a"],
        "video": [".mp4", ".mov", ".avi", ".webm", ".mkv"],
        "text": [".txt"],
    })
    allowed_mimes: Dict[str, List[str]] = field(default_factory=lambda: {
        "image": ["image/jpeg", "image/png", "image/webp", "image/bmp"],
        "audio": ["audio/wav", "audio/x-wav", "audio/mpeg", "audio/mp3", "audio/flac", "audio/ogg", "audio/x-m4a", "audio/m4a"],
        "video": ["video/mp4", "video/quicktime", "video/x-msvideo", "video/webm", "video/x-matroska"],
        "text": ["text/plain"],
    })


@dataclass(frozen=True)
class Settings:
    app: AppConfig = field(default_factory=AppConfig)
    thresholds: ThresholdConfig = field(default_factory=lambda: ThresholdConfig(upper_threshold=0.45, lower_threshold=0.40))
    video_thresholds: ThresholdConfig = field(default_factory=lambda: ThresholdConfig(upper_threshold=0.45, lower_threshold=0.40))
    image_model: ImageModelConfig = field(default_factory=ImageModelConfig)
    text_model: TextModelConfig = field(default_factory=TextModelConfig)
    audio_model: AudioModelConfig = field(default_factory=AudioModelConfig)
    video_model: VideoModelConfig = field(default_factory=VideoModelConfig)
    security: SecurityConfig = field(default_factory=SecurityConfig)


def load_settings(config_path: Optional[Path] = None) -> Settings:
    """
    Loads and validates settings from a YAML configuration file.
    If no path is specified, defaults to configs/config.yaml.
    """
    if config_path is None:
        base_dir = Path(__file__).resolve().parent.parent.parent
        config_path = base_dir / "configs" / "config.yaml"

    if not config_path.exists():
        return Settings()

    try:
        with open(config_path, "r", encoding="utf-8") as f:
            raw_cfg: Dict[str, Any] = yaml.safe_load(f) or {}
    except Exception as e:
        raise ValidationError(f"Failed to parse configuration YAML at {config_path}: {e}")

    app_data = raw_cfg.get("app", {})
    thresh_data = raw_cfg.get("thresholds", {})
    models_data = raw_cfg.get("models", {})
    sec_data = raw_cfg.get("security", {})

    app_cfg = AppConfig(
        name=app_data.get("name", "Authentica AI"),
        tagline=app_data.get("tagline", "Multimodal AI-Generated Content Detection System"),
        version=app_data.get("version", "1.0.0"),
        disclaimer=app_data.get("disclaimer", "This result is an AI-based estimate and is not definitive proof of whether the content was generated by AI."),
    )

    thresh_cfg = ThresholdConfig(
        upper_threshold=float(thresh_data.get("upper_threshold", 0.45)),
        lower_threshold=float(thresh_data.get("lower_threshold", 0.40)),
    )
    thresh_cfg.validate()

    vid_thresh_data = raw_cfg.get("video_thresholds", {})
    vid_thresh_cfg = ThresholdConfig(
        upper_threshold=float(vid_thresh_data.get("upper_threshold", 0.45)),
        lower_threshold=float(vid_thresh_data.get("lower_threshold", 0.40)),
    )
    vid_thresh_cfg.validate()

    img_data = models_data.get("image", {})
    img_cfg = ImageModelConfig(
        primary=img_data.get("primary", "umm-maybe/AI-image-detector"),
        baseline=img_data.get("baseline", "capcheck/ai-image-detection"),
        device=img_data.get("device", "auto"),
        batch_size=int(img_data.get("batch_size", 1)),
        input_size=tuple(img_data.get("input_size", [224, 224])),
    )

    txt_data = models_data.get("text", {})
    txt_cfg = TextModelConfig(
        primary=txt_data.get("primary", "Hello-SimpleAI/chatgpt-detector-roberta"),
        multilingual=txt_data.get("multilingual", "yaya36095/xlm-roberta-text-detector"),
        device=txt_data.get("device", "auto"),
        max_length=int(txt_data.get("max_length", 512)),
        min_character_length=int(txt_data.get("min_character_length", 50)),
        chunk_overlap=int(txt_data.get("chunk_overlap", 50)),
    )

    aud_data = models_data.get("audio", {})
    aud_cfg = AudioModelConfig(
        primary=aud_data.get("primary", "garystafford/wav2vec2-deepfake-voice-detector"),
        baseline=aud_data.get("baseline", "Sara1708/deepfake-audio-wav2vec2"),
        device=aud_data.get("device", "auto"),
        target_sample_rate=int(aud_data.get("target_sample_rate", 16000)),
        chunk_duration_sec=float(aud_data.get("chunk_duration_sec", 4.0)),
    )

    vid_data = models_data.get("video", {})
    vid_cfg = VideoModelConfig(
        sample_frames=int(vid_data.get("sample_frames", 8)),
        max_duration_sec=int(vid_data.get("max_duration_sec", 50)),
        visual_weight=float(vid_data.get("visual_weight", 0.6)),
        audio_weight=float(vid_data.get("audio_weight", 0.4)),
    )
    vid_cfg.validate()

    sec_cfg = SecurityConfig(
        max_image_size_mb=int(sec_data.get("max_image_size_mb", 25)),
        max_audio_size_mb=int(sec_data.get("max_audio_size_mb", 50)),
        max_video_size_mb=int(sec_data.get("max_video_size_mb", 250)),
        max_text_characters=int(sec_data.get("max_text_characters", 50000)),
        allowed_extensions=sec_data.get("allowed_extensions", SecurityConfig().allowed_extensions),
        allowed_mimes=sec_data.get("allowed_mimes", SecurityConfig().allowed_mimes),
    )

    return Settings(
        app=app_cfg,
        thresholds=thresh_cfg,
        video_thresholds=vid_thresh_cfg,
        image_model=img_cfg,
        text_model=txt_cfg,
        audio_model=aud_cfg,
        video_model=vid_cfg,
        security=sec_cfg,
    )
